In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
dataset = load_dataset("spandyie/nepali-news-dataset")

Resolving data files:   0%|          | 0/28 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/17 [00:00<?, ?it/s]

In [3]:
dataset

DatasetDict({
    train: Dataset({
        features: ['heading', 'text', 'date', 'link', 'clean_categories', 'category'],
        num_rows: 2760921
    })
})

In [4]:
df = dataset["train"].to_pandas()

In [5]:
df.head()

,heading,text,date,link,clean_categories,category
0,छापामारदेखि मन्त्रीसम्म...,\nसुर्खेत (रासस) । विसं २०४६ मा तत्कालीन मसालक...,"बिहीबार, फागुन १०, २०७४",https://baahrakhari.com/news-details/49124,politics,राजनीति
1,सूचना टाँस गरी बैठक स्थगन,\nसुर्खेत । प्रदेश नं ६ को आज बस्ने प्रदेशसभा ...,"बिहीबार, फागुन १०, २०७४",https://baahrakhari.com/news-details/49117,politics,राजनीति
2,पुराना दलबाट मुलुकले निकास पाउँदैन : डा भट्टराई,\nलुम्बिनी । नयाँ शक्ति पार्टी नेपालका संयोजक ...,"बिहीबार, फागुन १०, २०७४",https://baahrakhari.com/news-details/49116,politics,राजनीति
3,"मन्त्रालयमा अझै कुरा मिलेन, फोरमलाई पनि सरकारम...",\nकाठमाडौं । मन्त्रालयको संख्या कति राख्ने र म...,"बुधबार, फागुन ९, २०७४",https://baahrakhari.com/news-details/49115,politics,राजनीति
4,एमाले प्रदेश संसदीय दलको मुख्य सचेतकमा शाह,\nसुर्खेत । प्रदेश नं. ६ को नेकपा एमाले प्रदेश...,"बुधबार, फागुन ९, २०७४",https://baahrakhari.com/news-details/49113,politics,राजनीति

In [6]:
df.shape

(2760921, 6)

In [7]:
df.columns

Index(['heading', 'text', 'date', 'link', 'clean_categories', 'category'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2760921 entries, 0 to 2760920
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   heading           object
 1   text              object
 2   date              object
 3   link              object
 4   clean_categories  object
 5   category          object
dtypes: object(6)
memory usage: 126.4+ MB

In [9]:
df.isnull().sum()

heading             0
text                0
date                0
link                0
clean_categories    0
category            0
dtype: int64

In [10]:
df.to_csv(
    "../data/raw/nepali_news.csv",
    index=False,
    encoding="utf-8-sig"
)

In [11]:
news_df = df[["heading", "text", "clean_categories"]].copy()

news_df.rename(
    columns={
        "text": "news_body",
        "clean_categories": "category"
    },
    inplace=True
)

news_df.head()

,heading,news_body,category
0,छापामारदेखि मन्त्रीसम्म...,\nसुर्खेत (रासस) । विसं २०४६ मा तत्कालीन मसालक...,politics
1,सूचना टाँस गरी बैठक स्थगन,\nसुर्खेत । प्रदेश नं ६ को आज बस्ने प्रदेशसभा ...,politics
2,पुराना दलबाट मुलुकले निकास पाउँदैन : डा भट्टराई,\nलुम्बिनी । नयाँ शक्ति पार्टी नेपालका संयोजक ...,politics
3,"मन्त्रालयमा अझै कुरा मिलेन, फोरमलाई पनि सरकारम...",\nकाठमाडौं । मन्त्रालयको संख्या कति राख्ने र म...,politics
4,एमाले प्रदेश संसदीय दलको मुख्य सचेतकमा शाह,\nसुर्खेत । प्रदेश नं. ६ को नेकपा एमाले प्रदेश...,politics

In [12]:
news_df.dropna(
    subset=["news_body","category"],
    inplace=True
)

news_df = news_df[
    news_df["news_body"].str.strip() != ""
]

In [13]:
news_df.drop_duplicates(
    subset=[ "news_body"],
    inplace=True
)

In [14]:
print(news_df.shape)

(2760799, 3)

In [15]:
category_counts = (
    news_df["category"]
    .value_counts()
    .sort_values(ascending=False)
)

print(category_counts)

category
news                      702113
misc                      402823
politics                  250658
national                  225203
society                   214441
economy                   213945
sports                    179664
global                    125661
None                      110339
health                     64702
entertainment              62844
thought                    30611
prabash                    29007
literature                 24493
crime                      15835
business                   14250
art                        10280
opinion                     9988
education                   8909
science and technology      8644
interview                   8436
security                    8284
blog                        7463
world                       6779
court                       5468
tourism                     4480
editorial                   3768
culture                     3226
diaspora                    2979
transportation              1866
religious                   1588
agriculture                 1160
technology                   824
lifestyle                     68
Name: count, dtype: int64

In [16]:
selected_categories = [
    "politics",
    "national",
    "society",
    "economy",
    "sports",
    "global",
    "health",
    "entertainment",
    "business",
    "education",
    "science and technology",
    "crime"
]

news_df = news_df[
    news_df["category"].isin(selected_categories)
]

In [17]:
news_df["category"].value_counts()

category
politics                  250658
national                  225203
society                   214441
economy                   213945
sports                    179664
global                    125661
health                     64702
entertainment              62844
crime                      15835
business                   14250
education                   8909
science and technology      8644
Name: count, dtype: int64

In [35]:
sample_list = []

for category, group in news_df.groupby("category"):
    sample = group.sample(
        n=8000,
        random_state=42
    )
    sample_list.append(sample)

sample_df = pd.concat(
    sample_list,
    ignore_index=True
)

print(sample_df.columns)
print(sample_df.shape)

Index(['heading', 'news_body', 'category'], dtype='str')
(96000, 3)

In [37]:
import re
import pandas as pd

def clean_text(text):
    if pd.isna(text):
        return text

    # Remove unusual Unicode line separators
    text = re.sub(r'[\u2028\u2029]', ' ', text)

    # Replace newlines and tabs with spaces
    text = re.sub(r'[\r\n\t]+', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

sample_df["news_body"] = sample_df["news_body"].apply(clean_text)
sample_df["heading"] = sample_df["heading"].apply(clean_text)

In [38]:
import os

os.makedirs("../data/processed", exist_ok=True)

sample_df.to_csv(
    "../data/processed/sample_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

In [39]:
sample_df.shape

(96000, 3)